server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost/user_bootcamp
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
        security:
          web: debug
